//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod applications;
pub mod clients;
pub mod documents;
pub mod invoices;
pub mod permissions;
pub mod projects;
pub mod role_permissions;
pub mod roles;
pub mod tenant_applications;
pub mod tenant_member_roles;
pub mod tenant_members;
pub mod tenants;
pub mod users;
