//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::applications::Entity as Applications;
pub use super::documents::Entity as Documents;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::tenant_applications::Entity as TenantApplications;
pub use super::tenant_member_roles::Entity as TenantMemberRoles;
pub use super::tenant_members::Entity as TenantMembers;
pub use super::tenants::Entity as Tenants;
pub use super::users::Entity as Users;
