// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

export type CreatePost = { title: string, content: string, status: PostStatus, price: string, };
