// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page of results: the items, plus the framework's pagination metadata
 * flattened alongside them.
 *
 * The field names are exactly `PagerMeta`'s (`page`, `page_size`,
 * `total_pages`, `total_items`), so an app has one pagination vocabulary
 * whether a handler answers with this typed envelope or with the framework's
 * own `Pager`. Build it with [`Page::from_query`] rather than by hand — that
 * is what keeps the two in step.
 */
export type Page<T> = { items: Array<T>, page: number, page_size: number, total_pages: number, total_items: number, };
