// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

export type PostDto = { id: number, title: string, content: string, status: PostStatus, price: string, published_at: string | null, created_at: string, };
