// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Page<T> = { items: Array<T>, total: number, page: number, per_page: number, };
