// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateStaff = { name: string, email: string, password: string, role: string, };
