// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardApplication = { id: number, name: string, status: string, permissions: Array<string>, };
