// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardApplication } from "./DashboardApplication";
import type { DashboardStats } from "./DashboardStats";
import type { MemberAccess } from "./MemberAccess";

export type DashboardDto = { tenant_id: number, tenant_name: string, stats: DashboardStats, current_member: MemberAccess, members: Array<MemberAccess>, applications: Array<DashboardApplication>, };
