// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardApplication } from "./DashboardApplication";
import type { DashboardStats } from "./DashboardStats";
import type { MemberAccess } from "./MemberAccess";
import type { PermissionAccess } from "./PermissionAccess";
import type { RoleAccess } from "./RoleAccess";

export type DashboardDto = { tenant_id: number, tenant_name: string, stats: DashboardStats, current_member: MemberAccess, members: Array<MemberAccess>, roles: Array<RoleAccess>, available_permissions: Array<PermissionAccess>, applications: Array<DashboardApplication>, };
