// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardStats = { member_count: number, application_count: number, document_count: number, invoice_count: number, };
