// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardStats = { member_count: number, addon_count: number, client_count: number, project_count: number, document_count: number, invoice_count: number, };
