// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvoiceDto = { id: number, tenant_id: number, tenant_application_id: number, number: string, amount_cents: number, status: string, created_at: string, updated_at: string, };
