// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionAccess } from "./PermissionAccess";

export type MemberAccess = { member_id: number, user_id: number, name: string, email: string, roles: Array<string>, permissions: Array<PermissionAccess>, };
