// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionAccess = { application_id: number, application_name: string, key: string, };
