// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDto = { id: number, tenant_id: number, name: string, description: string, created_at: string, updated_at: string, };
