// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterTenant = { name: string, email: string, password: string, tenant_name: string, tenant_slug: string, };
