// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterTenantResponse = { token: string, pid: string, name: string, tenant_id: number, tenant_name: string, application_id: number, application_name: string, };
