// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionAccess } from "./PermissionAccess";

export type RoleAccess = { id: number, name: string, permissions: Array<PermissionAccess>, };
