// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaffCreated = { member_id: number, user_id: number, name: string, email: string, role: string, };
