// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationAccess } from "./ApplicationAccess";

export type Workspace = { tenant_id: number, tenant_name: string, tenant_slug: string, applications: Array<ApplicationAccess>, };
